### ISSUE TITLE
Compiling Error

### ISSUE THREAD

**Issue by zy5460** [NordicSemiconductor/nRF52-ADC-examples#2]
When it's compiled, There is an error "fatal error: nrf_drv_clock.h: No such file or directory"
I used the Makefile in "saadc_low_power/pca10040/armgcc".

**Comment by bootchk** [comment]
It might be because you are using SDK version 12, where the names of include files were changed from version 11.  In your case I think the file name is changed to .../hal/nrf_clock.h  .

I think there are several other instances where names have changed.   Unfortunately, you should not expect the code to compile on SDK 12 without a few edits?  I think the code is mostly for reading, to teach what broad steps are needed to save power when using the ADC.

**Comment by zy5460** [comment]
Thanks for your sharing. It has helped me a lot.

**Comment by bootchk** [comment]
You're welcome.  I was struggling with the SAADC myself today.  See supplyVoltage.c in my nrfrawProtocol project on Github.
